<a href="https://colab.research.google.com/github/ElMartinez31/Data_Science/blob/main/Projects/Hugging_Face/HF_text_summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from transformers import AutoTokenizer, AutoModelForTokenClassification
from transformers import pipeline
import kagglehub
import pandas as pd
import os

# Download latest version
path = kagglehub.dataset_download("modhiibrahimalmannaa/1000-children-books-on-amazom")

print("Path to dataset files:", path)

os.listdir(path)

df = pd.read_csv(path + "/" + "books_data.csv")
df

Downloading from https://www.kaggle.com/api/v1/datasets/download/modhiibrahimalmannaa/1000-children-books-on-amazom?dataset_version_number=1...

100%|██████████| 712k/712k [00:00<00:00, 38.8MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/modhiibrahimalmannaa/1000-children-books-on-amazom/versions/1

,Name,Series,Description,Author,Age,Rating_out_of_5,No_of_Ratings,Price,Price_Befor,Cover_Type,Publication_Date,Product_Details,Best_Seller,Link
0,We Were Liars,NaN,"\n#1 NEW YORK TIMES BESTSELLER • A modern, sop...",E. Lockhart,Ages: 12 years and up,4.5,12.959,$5.99,$10.99,Paperback,2018-05-29,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/We-Were-Liars-Lockhart/...
1,Harry Potter Paperback Box Set (Books 1-7),NaN,"\nNow for the first time ever, J.K. Rowling’s ...",J. K. Rowling,Ages: 8 years and up,4.9,34.849,$50.00,$86.93,Paperback,2009-07-01,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Harry-Potter-Paperback-...
2,If Animals Kissed Good Night,NaN,\nDon't miss the other books in this adorable ...,Ann Whitford Paul,Ages: 3 - 6 years,4.8,34.548,$4.79,$7.99,Board book,2014-06-03,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,in Poetry for Early Learning,https://www.amazon.com/If-Animals-Kissed-Good-...
3,My First Learn to Write Workbook: Practice for...,NaN,\nA lifetime of communication skills starts he...,Crystal Radke,Ages: 3 - 5 years,4.8,41.827,$5.39,$8.99,Paperback,2019-08-27,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,in Language Arts Teaching Materials,https://www.amazon.com/My-First-Learn-Write-Wo...
4,I Love You to the Moon and Back,NaN,\nShow your child just how strong your love is...,Amelia Hepworth,Ages: 2 - 5 years,4.9,20.949,$1.38,NaN,Board book,2015-03-03,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,in Children's Bear Books,https://www.amazon.com/I-Love-You-Moon-Back/dp...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,Snow (Sunburst Books),NaN,\nSnow is a 1998 New York Times Outstanding Bo...,Uri Shulevitz,Ages: 4 - 7 years,4.7,553.000,$0.00,$7.93,Paperback,2004-09-23,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Snow-Sunburst-Books-Uri...
1196,How Full Is Your Bucket? For Kids,NaN,\nAn illustrated adaptation of the long-runnin...,Tom Rath,Ages: 3 - 8 years,4.8,1.400,$17.95,$10.49,Hardcover,2009-04-01,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/How-Full-Your-Bucket-Ki...
1197,"Indestructibles: Love You, Baby: Chew Proof · ...",NaN,\nShow baby loads of love in a book that’s ind...,Stephan Lomp,Ages: 0 - 2 years,4.9,2.240,$5.89,NaN,Paperback,2017-08-08,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Indestructibles-Love-Ba...
1198,"Disney - Mickey Mouse, Toy Story and More! Me ...",NaN,\nHave an adventure with characters from Disne...,Editors of Phoenix International Publications,NaN,4.7,747.000,$21.99,$25.98,Hardcover,2013-06-01,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Disney-Electronic-Reade...
1199,Dinosaur Lady: The Daring Discoveries of Mary ...,NaN,\nA beautifully illustrated picture book biogr...,Linda Skeers,Ages: 4 - 8 years,4.9,269.000,$15.67,$17.99,Hardcover,2020-07-07,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Dinosaur-Lady-Linda-Ske...

In [2]:
df["Description"] = df["Description"].str.replace('\n', ' ', regex=False)
df

,Name,Series,Description,Author,Age,Rating_out_of_5,No_of_Ratings,Price,Price_Befor,Cover_Type,Publication_Date,Product_Details,Best_Seller,Link
0,We Were Liars,NaN,"#1 NEW YORK TIMES BESTSELLER • A modern, soph...",E. Lockhart,Ages: 12 years and up,4.5,12.959,$5.99,$10.99,Paperback,2018-05-29,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/We-Were-Liars-Lockhart/...
1,Harry Potter Paperback Box Set (Books 1-7),NaN,"Now for the first time ever, J.K. Rowling’s s...",J. K. Rowling,Ages: 8 years and up,4.9,34.849,$50.00,$86.93,Paperback,2009-07-01,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Harry-Potter-Paperback-...
2,If Animals Kissed Good Night,NaN,Don't miss the other books in this adorable s...,Ann Whitford Paul,Ages: 3 - 6 years,4.8,34.548,$4.79,$7.99,Board book,2014-06-03,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,in Poetry for Early Learning,https://www.amazon.com/If-Animals-Kissed-Good-...
3,My First Learn to Write Workbook: Practice for...,NaN,A lifetime of communication skills starts her...,Crystal Radke,Ages: 3 - 5 years,4.8,41.827,$5.39,$8.99,Paperback,2019-08-27,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,in Language Arts Teaching Materials,https://www.amazon.com/My-First-Learn-Write-Wo...
4,I Love You to the Moon and Back,NaN,Show your child just how strong your love is ...,Amelia Hepworth,Ages: 2 - 5 years,4.9,20.949,$1.38,NaN,Board book,2015-03-03,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,in Children's Bear Books,https://www.amazon.com/I-Love-You-Moon-Back/dp...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,Snow (Sunburst Books),NaN,Snow is a 1998 New York Times Outstanding Boo...,Uri Shulevitz,Ages: 4 - 7 years,4.7,553.000,$0.00,$7.93,Paperback,2004-09-23,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Snow-Sunburst-Books-Uri...
1196,How Full Is Your Bucket? For Kids,NaN,An illustrated adaptation of the long-running...,Tom Rath,Ages: 3 - 8 years,4.8,1.400,$17.95,$10.49,Hardcover,2009-04-01,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/How-Full-Your-Bucket-Ki...
1197,"Indestructibles: Love You, Baby: Chew Proof · ...",NaN,Show baby loads of love in a book that’s inde...,Stephan Lomp,Ages: 0 - 2 years,4.9,2.240,$5.89,NaN,Paperback,2017-08-08,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Indestructibles-Love-Ba...
1198,"Disney - Mickey Mouse, Toy Story and More! Me ...",NaN,Have an adventure with characters from Disney...,Editors of Phoenix International Publications,NaN,4.7,747.000,$21.99,$25.98,Hardcover,2013-06-01,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Disney-Electronic-Reade...
1199,Dinosaur Lady: The Daring Discoveries of Mary ...,NaN,A beautifully illustrated picture book biogra...,Linda Skeers,Ages: 4 - 8 years,4.9,269.000,$15.67,$17.99,Hardcover,2020-07-07,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Dinosaur-Lady-Linda-Ske...

In [4]:
model_summary = "facebook/bart-large-cnn" # encoder decoder
summarizer = pipeline("summarization",
                      model = model_summary,
                      device = "cpu")

model_sentiment = ""

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu

In [3]:
summarizer(df.Description[0])

' #1\xa0NEW YORK TIMES\xa0BESTSELLER • A modern, sophisticated suspense novel from National Book Award finalist, and Printz Award honoree E. Lockhart.A beautiful and distinguished family.A private island.A brilliant, damaged girl; a passionate, political boy.A group of four friends—the Liars—whose friendship turns destructive.A revolution. An accident. A secret.Lies upon lies.True love.The truth.Read it.And if anyone asks you how it ends, just LIE."Thrilling, beautiful, and blisteringly smart, We Were Liars is utterly unforgettable." —John Green, #1 New York Times bestselling author of The Fault in Our Stars  '

In [7]:
summarizer(df.Description[0])[0]["summary_text"]

'"Thrilling, beautiful, and blisteringly smart, We Were Liars is utterly unforgettable." —John Green, #1 New York Times bestselling author of The Fault in Our Stars. A modern, sophisticated suspense novel from National Book Award finalist, and Printz Award honoree E. Lockhart.'

In [9]:
df.loc[:5, "Summary"] = df.Description[:5].apply(lambda row : summarizer(row, max_length = 70)[0]["summary_text"])

In [12]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
df[["Description", "Summary"]]

,Description,Summary
0,"#1 NEW YORK TIMES BESTSELLER • A modern, sophisticated suspense novel from National Book Award finalist, and Printz Award honoree E. Lockhart.A beautiful and distinguished family.A private island.A brilliant, damaged girl; a passionate, political boy.A group of four friends—the Liars—whose friendship turns destructive.A revolution. An accident. A secret.Lies upon lies.True love.The truth.Read it.And if anyone asks you how it ends, just LIE.""Thrilling, beautiful, and blisteringly smart, We Were Liars is utterly unforgettable."" —John Green, #1 New York Times bestselling author of The Fault in Our Stars","""Thrilling, beautiful, and blisteringly smart, We Were Liars is utterly unforgettable."" —John Green, #1 New York Times bestselling author of The Fault in Our Stars. A modern, sophisticated suspense novel from National Book Award finalist, and Printz Award honoree E. Lockhart."
1,"Now for the first time ever, J.K. Rowling’s seven bestselling Harry Potter books are available in a stunning paperback boxed set! The Harry Potter series has been hailed as “one for the ages” by Stephen King and “a spellbinding saga’ by USA Today. And most recently, The New York Times called Harry Potter and the Deathly Hallows the “fastest selling book in history.” This is the ultimate Harry Potter collection for Harry Potter fans of all ages!",J.K. Rowling’s seven bestselling Harry Potter books are available in a stunning paperback boxed set. The Harry Potter series has been hailed as “one for the ages” by Stephen King and “a spellbinding saga’ by USA Today. The New York Times called Harry Potter and the Deathly Hallows
2,"Don't miss the other books in this adorable series: If Animals Said I Love You, If Animals Celebrated Christmas, If Animals Went to School, and If Animals Gave Thanks!What if animals did what YOU do? This bestselling story imagines how animals would kiss their loved ones good night!If animals kissed good night like we do...how would they do it? Giraffe and his calf would stretch their necks high, Wolf and his pup would kiss and then HOWL, and Sloth and her baby would move sooooo sloooowwwww. And across the animal kingdom, every creature would share love in a unique way.","If animals kissed good night like we do...how would they do it? Giraffe and his calf would stretch their necks high, Wolf and his pup would kiss and then HOWL. Sloth and her baby would move sooooo sloooowwwww. And across the animal kingdom, every creature would share love in a unique way"
3,"A lifetime of communication skills starts here―the ultimate writing workbook for kids 3 to 5Set kids up to succeed in school with a learn to write for kids guide that teaches them letters, shapes, and numbers―and makes it fun. My First Learn-to-Write Workbook introduces early writers to proper pen control, line tracing, and more with dozens of handwriting exercises that engage their minds and boost their reading and writing comprehension skills.This activity book for kids includes:75+ Pages of practices―Tons of engaging pencil-on-paper activities like connect-the-dots and fill-in-the-blank offer enough repetition for real learning but enough variety to keep kids interested.Colorful fun―This workbook is full of helpful (and silly) pictures and illustrations that will spark kids’ imaginations and get them excited to keep practicing. Comprehensive skill-building―As they explore these exercises, kids will learn reading comprehension and letters as well as numbers, pen control, and fine motor skills.Get your little one on the path to success with this exciting learn to write workbook.","The ultimate writing workbook for kids 3 to 5. Set kids up to succeed in school with a learn to write for kids guide that teaches them letters, shapes, and numbers. My First Learn-to-Write Workbook introduces early writers to proper pen control, line tracing, and more."
4,"Show your child just how strong your love is every minute of the day! Features a ""To"" and ""From"" personalization page, making this sweet offering an ideal gift for baby showers, birthdays, and new parents. The sun rises, and a bear and cub begin their day together. They splash in the water, climb mountains, watch the colorful lights in the shimmering sky, and play with friends. They show their love for each other by touching noses, chasing each other, and, of course, hugging and snuggling before bed. A sweet, gentle rhyme, perfect for sharing with a special little one that also includes a “To” and ""From” personalization page in the front of the book, making this heartwarming book an ideal gift.","The sun rises, and a bear and cub begin their day together. Show your child just how strong your love is every minute of the day! Features a ""To"" and ""From"" personalization page, making this sweet offering an ideal gift for baby showers, birthdays, and new parents."
...,...,...
1195,"Snow is a 1998 New York Times Outstanding Book of the Year and a 1999 Caldecott Honor Book.""It's snowing, said boy with dog.""It's only a snowflake,"" said grandfather with beard.No one thinks one or two snowflakes will amount to anything. Not the man with the hat or the lady with the umbrella. Not even the television or the radio forecasters. But one boy and his dog have faith that the snow will amount to something spectacular, and when flakes start to swirl down on the city, they are also the only ones who know how to truly enjoy it. Uri Shulevitz' playful depiction of a snowy day and the transformation of a city is perfectly captured in simple, poetic text and lively watercolor and pen-and-ink illustrations.",NaN
1196,"An illustrated adaptation of the long-running bestseller How Full Is Your Bucket? (more than 400,000 copies sold) for kids — told through the story of a boy who learns a valuable “bucket filling” metaphor and watches it come to life as the day unfolds.Every moment matters. Each of us has an invisible bucket. When our bucket is full, we feel great. When it’s empty, we feel awful. Yet most children (and many adults) don’t realize the importance of having a full bucket throughout the day. In How Full Is Your Bucket? For Kids, Felix begins to see how every interaction in a day either fills or empties his bucket. Felix then realizes that everything he says or does to other people fills or empties their buckets as well. Follow along with Felix as he learns how easy it can be to fill the buckets of his classmates, teachers and family members. Before the day is over, you’ll see how Felix learns to be a great bucket filler, and in the process, discovers that filling someone else’s bucket also fills his own.",NaN
1197,"Show baby loads of love in a book that’s indestructible! Baby loves hugs. Just like baby kitty! Baby loves nuzzles. Just like baby bunny! Baby loves snuggles. Just like baby piggy! Indestructibles is the trusted series for easing little ones into story time. Beloved by babies and their parents, Indestructibles are built for the way babies “read” (i.e., with their hands and mouths) and are:Rip Proof—made of ultra-durable tight-woven materialWaterproof—can be chewed on, drooled on, and washed!Emergent Literacy Tool—bright pictures and few or no words encourage dialogic readingPortable—lightweight books can go anywhere, perfect for the diaper bag and for travelSafe for Baby—meets ASTM safety standards",NaN
1198,"Have an adventure with characters from Disney and Pixar favorites like Toy Story, Mickey Mouse Clubhouse, and more! Eight illustrated books featuring come packaged with a sleek Me Reader Module that reads each book aloud. Choose a book, press the matching book and page buttons on the module, and hear the whole story, along with fun and surprising sounds! Follow along in the book for a fun, independent reading experience that builds confidence in beginning readers. Story sounds and expressive narration enhance reading comprehension. This Electronic Reader Library is special because: Hands on interaction engages young readers Connecting words with pictures builds vocabulary Multisensory reading experiences stimulate the imaginations of young readers Includes Disney and Pixar favorites: Mickey and Minnie Mouse, Daisy and Donald Duck, Goofy, and Pluto from Mickey Mouse Clubhouse; Woody, Buzz Lightyear, and more from Toy Story; Disney princess Rapunzel and more from Tangled; Mr. Incredible, Elastigirl, Jack Jack, Violet, and Dash from The Incredibles; Lightning McQueen, Mater and More form Cars;Mike, Sully and Boo from Monsters Inc.; Wall-E and Eve; and Russel Carl and Dug from Up",NaN
1199,"A beautifully illustrated picture book biography of Mary Anning that will enlighten children about the discovery of the dinosaurs and the importance of female scientists, perfect for fans of The Girl Who Thought in PicturesMary Anning loved scouring the beach near her home in England for shells and fossils. She fearlessly climbed over crumbling cliffs and rocky peaks, searching for new specimens. One day, something caught Mary's eye.Bones. Dinosaur Bones.Mary's discoveries rocked the world of science and helped create a brand-new field of study: paleontology. But many people believed women couldn't be scientists, so Mary wasn't given the credit she deserved. Nevertheless, Mary kept looking and learning more, making discoveries that reshaped scientific beliefs about the natural world.Educational backmatter includes a timeline of Mary Anning's life and lots of fantastic fossil facts!The perfect choice for parents and teachers looking for:Dinosaur books for kids 5-7 and kids books about fossilsFeminist picture books about historical women, and daring books for girlsKids STEM books",NaN