<a href="https://colab.research.google.com/github/ElMartinez31/Data_Science/blob/main/Projects/Hugging_Face/HF_zero_shot_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from transformers import AutoTokenizer, AutoModelForTokenClassification
from transformers import pipeline

In [7]:
import kagglehub
import pandas as pd
import os

# Download latest version
path = kagglehub.dataset_download("modhiibrahimalmannaa/1000-children-books-on-amazom")

print("Path to dataset files:", path)

os.listdir(path)

df = pd.read_csv(path + "/" + "books_data.csv")
df

Downloading from https://www.kaggle.com/api/v1/datasets/download/modhiibrahimalmannaa/1000-children-books-on-amazom?dataset_version_number=1...

100%|██████████| 712k/712k [00:00<00:00, 50.7MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/modhiibrahimalmannaa/1000-children-books-on-amazom/versions/1

,Name,Series,Description,Author,Age,Rating_out_of_5,No_of_Ratings,Price,Price_Befor,Cover_Type,Publication_Date,Product_Details,Best_Seller,Link
0,We Were Liars,NaN,"\n#1 NEW YORK TIMES BESTSELLER • A modern, sop...",E. Lockhart,Ages: 12 years and up,4.5,12.959,$5.99,$10.99,Paperback,2018-05-29,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/We-Were-Liars-Lockhart/...
1,Harry Potter Paperback Box Set (Books 1-7),NaN,"\nNow for the first time ever, J.K. Rowling’s ...",J. K. Rowling,Ages: 8 years and up,4.9,34.849,$50.00,$86.93,Paperback,2009-07-01,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Harry-Potter-Paperback-...
2,If Animals Kissed Good Night,NaN,\nDon't miss the other books in this adorable ...,Ann Whitford Paul,Ages: 3 - 6 years,4.8,34.548,$4.79,$7.99,Board book,2014-06-03,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,in Poetry for Early Learning,https://www.amazon.com/If-Animals-Kissed-Good-...
3,My First Learn to Write Workbook: Practice for...,NaN,\nA lifetime of communication skills starts he...,Crystal Radke,Ages: 3 - 5 years,4.8,41.827,$5.39,$8.99,Paperback,2019-08-27,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,in Language Arts Teaching Materials,https://www.amazon.com/My-First-Learn-Write-Wo...
4,I Love You to the Moon and Back,NaN,\nShow your child just how strong your love is...,Amelia Hepworth,Ages: 2 - 5 years,4.9,20.949,$1.38,NaN,Board book,2015-03-03,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,in Children's Bear Books,https://www.amazon.com/I-Love-You-Moon-Back/dp...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,Snow (Sunburst Books),NaN,\nSnow is a 1998 New York Times Outstanding Bo...,Uri Shulevitz,Ages: 4 - 7 years,4.7,553.000,$0.00,$7.93,Paperback,2004-09-23,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Snow-Sunburst-Books-Uri...
1196,How Full Is Your Bucket? For Kids,NaN,\nAn illustrated adaptation of the long-runnin...,Tom Rath,Ages: 3 - 8 years,4.8,1.400,$17.95,$10.49,Hardcover,2009-04-01,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/How-Full-Your-Bucket-Ki...
1197,"Indestructibles: Love You, Baby: Chew Proof · ...",NaN,\nShow baby loads of love in a book that’s ind...,Stephan Lomp,Ages: 0 - 2 years,4.9,2.240,$5.89,NaN,Paperback,2017-08-08,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Indestructibles-Love-Ba...
1198,"Disney - Mickey Mouse, Toy Story and More! Me ...",NaN,\nHave an adventure with characters from Disne...,Editors of Phoenix International Publications,NaN,4.7,747.000,$21.99,$25.98,Hardcover,2013-06-01,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Disney-Electronic-Reade...
1199,Dinosaur Lady: The Daring Discoveries of Mary ...,NaN,\nA beautifully illustrated picture book biogr...,Linda Skeers,Ages: 4 - 8 years,4.9,269.000,$15.67,$17.99,Hardcover,2020-07-07,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Dinosaur-Lady-Linda-Ske...

In [4]:
model = "facebook/bart-large-mnli" # encoder decoder
classifier = pipeline("zero-shot-classification",
                      model = model,
                      device = "cpu")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu

In [5]:
#example

text1 = "When life gives you lemons, make lemonade!"
text2 = "In god we trust"
text3 = "Hambuger is made of steak, brad and cheese"

texts = [text1, text2, text3]

In [6]:
# example

for text in texts:
  res = classifier(text, ["quote", "food & drinks", "religion", "animals"])
  print(res)

{'sequence': 'When life gives you lemons, make lemonade!', 'labels': ['quote', 'food & drink', 'animals', 'religion'], 'scores': [0.9498028755187988, 0.04016111046075821, 0.007770824711769819, 0.0022652416955679655]}
{'sequence': 'In god we trust', 'labels': ['religion', 'quote', 'animals', 'food & drink'], 'scores': [0.5802372694015503, 0.4145967960357666, 0.0025988535489887, 0.002567154821008444]}
{'sequence': 'Hambuger is made of steak, brad and cheese', 'labels': ['food & drink', 'quote', 'animals', 'religion'], 'scores': [0.8505029678344727, 0.12114870548248291, 0.026166290044784546, 0.002182047814130783]}

In [20]:
labels = ["quote", "food & drinks", "religion", "animals", "Adventures", "Litterature"]

df.loc[:5,"Category"] = df.Description[:5].apply(lambda row : classifier(row, labels)["labels"][0]) # get the main detected label + assign it to df

In [36]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

df["Description"] = df["Description"].str.replace('\n', ' ', regex=False).replace(' ','')
print(df.loc[:5,"Description"])

0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              #1 NEW YORK TIMES BESTSELLER • A modern, sophisticated suspense novel from National Book Award finalist, and Printz Award honoree E. Lockhart.A beautiful and distinguished family.A private island.A brilliant, damaged girl; a passionate, political boy.A group of four friends—the Liars—whose friendship turns destructive.A revolution. An accident. A secret.Lies upon lies.True love.The truth.Read it.And if anyone asks you how it ends, just LIE."Thrilling, beautiful, and blisteringly smart, We Were Liars is utterly unforgettable." —John Green, #1 New York Times bestselling author of The Fault in Our Stars
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Now for the first time ever, J.K. Rowling’s seven bestselling Harry Potter books are available in a stunning paperback boxed set! The Harry Potter series has been hailed as “one for the ages” by Stephen King and “a spellbinding saga’ by USA Today. And most recently, The New York Times called Harry Potter and the Deathly Hallows the “fastest selling book in history.” This is the ultimate Harry Potter collection for Harry Potter fans of all ages!
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Don't miss the other books in this adorable series: If Animals Said I Love You, If Animals Celebrated Christmas, If Animals Went to School, and If Animals Gave Thanks!What if animals did what YOU do? This bestselling story imagines how animals would kiss their loved ones good night!If animals kissed good night like we do...how would they do it? Giraffe and his calf would stretch their necks high, Wolf and his pup would kiss and then HOWL, and Sloth and her baby would move sooooo sloooowwwww. And across the animal kingdom, every creature would share love in a unique way.
3     A lifetime of communication skills starts here―the ultimate writing workbook for kids 3 to 5Set kids up to succeed in school with a learn to write for kids guide that teaches them letters, shapes, and numbers―and makes it fun. My First Learn-to-Write Workbook introduces early writers to proper pen control, line tracing, and more with dozens of handwriting exercises that engage their minds and boost their reading and writing comprehension skills.This activity book for kids includes:75+ Pages of practices―Tons of engaging pencil-on-paper activities like connect-the-dots and fill-in-the-blank offer enough repetition for real learning but enough variety to keep kids interested.Colorful fun―This workbook is full of helpful (and silly) pictures and illustrations that will spark kids’ imaginations and get them excited to keep practicing. Comprehensive skill-building―As they explore these exercises, kids will learn reading comprehension and letters as well as numbers, pen control, and fine motor skills.Get your little one on the path to success with this exciting learn to write workbook.
4                                                                                                                                                                                                                                                                                                                                                                                                              Show your child just how strong your love is every minute of the day! Features a "To" and "From" personalization page, making this sweet offering an ideal gift for baby showers, birthdays, and new parents. The sun rises, and a bear and cub begin their day together. They splash in the water, climb mountains, watch the colorful lights in the shimmering sky, and play with friends. They show their love for each other by touching noses, chasing each other, and, of course, hugging and snuggling before bed. A sweet, gentle rhyme, perfect for sharing with a special little one that also includes a “To” and "From” personalization page in the front of the book, making this heartwarming book an ideal gift.
5          From Vice President Kamala Harris comes a picture book with an empowering message: Superheroes are all around us--and if we try, we can all be heroes too. Now a #1 New York Times bestseller!Before Kamala Harris was elected to the vice presidency, she was a little girl who loved superheroes. And when she looked around, she was amazed to find them everywhere! In her family, among her friends, even down the street--there were superheroes wherever she looked. And those superheroes showed her that all you need to do to be a superhero is to be the best that you can be.In this empowering and joyful picture book that speaks directly to kids, Kamala Harris takes readers through her life and shows them that the power to make the world a better place is inside all of us. And with fun and engaging art by Mechal Renee Roe, as well as a guide to being a superhero at the end, this book is sure to have kids taking up the superhero mantle (cape and mask optional).Praise for Superheroes Are Everywhere:"This [book] offers a solid message: a superhero could be anyone, including you." --Booklist
Name: Description, dtype: object

In [19]:
df

,Name,Series,Description,Author,Age,Rating_out_of_5,No_of_Ratings,Price,Price_Befor,Cover_Type,Publication_Date,Product_Details,Best_Seller,Link,Category
0,We Were Liars,NaN,"\n#1 NEW YORK TIMES BESTSELLER • A modern, sop...",E. Lockhart,Ages: 12 years and up,4.5,12.959,$5.99,$10.99,Paperback,2018-05-29,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/We-Were-Liars-Lockhart/...,B
1,Harry Potter Paperback Box Set (Books 1-7),NaN,"\nNow for the first time ever, J.K. Rowling’s ...",J. K. Rowling,Ages: 8 years and up,4.9,34.849,$50.00,$86.93,Paperback,2009-07-01,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Harry-Potter-Paperback-...,B
2,If Animals Kissed Good Night,NaN,\nDon't miss the other books in this adorable ...,Ann Whitford Paul,Ages: 3 - 6 years,4.8,34.548,$4.79,$7.99,Board book,2014-06-03,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,in Poetry for Early Learning,https://www.amazon.com/If-Animals-Kissed-Good-...,B
3,My First Learn to Write Workbook: Practice for...,NaN,\nA lifetime of communication skills starts he...,Crystal Radke,Ages: 3 - 5 years,4.8,41.827,$5.39,$8.99,Paperback,2019-08-27,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,in Language Arts Teaching Materials,https://www.amazon.com/My-First-Learn-Write-Wo...,B
4,I Love You to the Moon and Back,NaN,\nShow your child just how strong your love is...,Amelia Hepworth,Ages: 2 - 5 years,4.9,20.949,$1.38,NaN,Board book,2015-03-03,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,in Children's Bear Books,https://www.amazon.com/I-Love-You-Moon-Back/dp...,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,Snow (Sunburst Books),NaN,\nSnow is a 1998 New York Times Outstanding Bo...,Uri Shulevitz,Ages: 4 - 7 years,4.7,553.000,$0.00,$7.93,Paperback,2004-09-23,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Snow-Sunburst-Books-Uri...,A
1196,How Full Is Your Bucket? For Kids,NaN,\nAn illustrated adaptation of the long-runnin...,Tom Rath,Ages: 3 - 8 years,4.8,1.400,$17.95,$10.49,Hardcover,2009-04-01,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/How-Full-Your-Bucket-Ki...,A
1197,"Indestructibles: Love You, Baby: Chew Proof · ...",NaN,\nShow baby loads of love in a book that’s ind...,Stephan Lomp,Ages: 0 - 2 years,4.9,2.240,$5.89,NaN,Paperback,2017-08-08,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Indestructibles-Love-Ba...,A
1198,"Disney - Mickey Mouse, Toy Story and More! Me ...",NaN,\nHave an adventure with characters from Disne...,Editors of Phoenix International Publications,NaN,4.7,747.000,$21.99,$25.98,Hardcover,2013-06-01,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Disney-Electronic-Reade...,A
1199,Dinosaur Lady: The Daring Discoveries of Mary ...,NaN,\nA beautifully illustrated picture book biogr...,Linda Skeers,Ages: 4 - 8 years,4.9,269.000,$15.67,$17.99,Hardcover,2020-07-07,\n\n\n\nProduct details\n\n\n\n\n\nPublisher\n...,NaN,https://www.amazon.com/Dinosaur-Lady-Linda-Ske...,A